cloud:
    aws:
      credentials:
        access-key: AKIATTOQUUPCKAKPRYZG
        secret-key: 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
      region:
        static: ap-southeast-1
      stack:
        auto: false

application:
  bucket:
    name: curnonwatch

#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB
      
